# Generated by Django 4.1.1 on 2022-11-23 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('imgUrl', models.TextField()),
                ('countryOfOrigin', models.CharField(max_length=30)),
                ('dateAdded', models.DateField(default=datetime.date.today)),
                ('avgRating', models.FloatField()),
                ('numOfVotes', models.IntegerField()),
            ],
        ),
    ]
