# Generated by Django 4.1.1 on 2022-11-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meal',
            table='meals',
        ),
    ]
