# Generated by Django 4.1.1 on 2022-11-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='typicalMealTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='avgRating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='numOfVotes',
            field=models.IntegerField(default=0),
        ),
    ]
